-- ==============================================================================
-- Portfolio Project: Retail Customer Shopping Behavior Analysis
-- SQL Queries for Business Insights and Segment Analysis
-- Database System: PostgreSQL
-- Author: Nistha Jain
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- Q1: What is the total revenue generated by male vs. female customers?
-- Purpose: Understand the revenue contribution of different gender demographics.
-- ------------------------------------------------------------------------------
SELECT 
    gender, 
    SUM(purchase_amount) AS total_revenue
FROM 
    customer
GROUP BY 
    gender;

-- ------------------------------------------------------------------------------
-- Q2: Which customers used a discount but still spent more than the average purchase amount?
-- Purpose: Identify high-value customers who leverage promotional offers.
-- ------------------------------------------------------------------------------
SELECT 
    customer_id, 
    purchase_amount
FROM 
    customer
WHERE 
    discount_applied = 'Yes' 
    AND purchase_amount >= (
        SELECT 
            AVG(purchase_amount) 
        FROM 
            customer
    );

-- ------------------------------------------------------------------------------
-- Q3: Which are the top 5 products with the highest average review rating?
-- Purpose: Pinpoint high-performing products based on customer feedback.
-- ------------------------------------------------------------------------------
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating::NUMERIC), 2) AS average_product_rating
FROM 
    customer
GROUP BY 
    item_purchased
ORDER BY 
    AVG(review_rating) DESC
LIMIT 5;

-- ------------------------------------------------------------------------------
-- Q4: Compare the average Purchase Amounts between Standard and Express Shipping.
-- Purpose: Analyze if premium shipping options correlate with higher order values.
-- ------------------------------------------------------------------------------
SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM 
    customer
WHERE 
    shipping_type IN ('Standard', 'Express')
GROUP BY 
    shipping_type;

-- ------------------------------------------------------------------------------
-- Q5: Do subscribed customers spend more? Compare average spend and total revenue 
--     between subscribers and non-subscribers.
-- Purpose: Measure the direct impact of the subscription program on sales.
-- ------------------------------------------------------------------------------
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM 
    customer
GROUP BY 
    subscription_status
ORDER BY 
    total_revenue DESC, 
    average_spend DESC;

-- ------------------------------------------------------------------------------
-- Q6: Which 5 products have the highest percentage of purchases with discounts applied?
-- Purpose: Identify product categories that rely heavily on promotional discounts.
-- ------------------------------------------------------------------------------
SELECT 
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate_percentage
FROM 
    customer
GROUP BY 
    item_purchased
ORDER BY 
    discount_rate_percentage DESC
LIMIT 5;

-- ------------------------------------------------------------------------------
-- Q7: Segment customers into New, Returning, and Loyal based on their total 
--     number of previous purchases, and show the count of each segment.
-- Purpose: Create transactional cohorts to understand user retention and loyalty.
-- ------------------------------------------------------------------------------
WITH customer_cohorts AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM 
        customer
)
SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM 
    customer_cohorts
GROUP BY 
    customer_segment
ORDER BY 
    customer_count DESC;

-- ------------------------------------------------------------------------------
-- Q8: What are the top 3 most purchased products within each product category?
-- Purpose: Highlight category leaders to optimize inventory and marketing.
-- ------------------------------------------------------------------------------
WITH ranked_items AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM 
        customer
    GROUP BY 
        category, 
        item_purchased
)
SELECT 
    category,
    item_purchased, 
    total_orders,
    item_rank
FROM 
    ranked_items
WHERE 
    item_rank <= 3;
 
-- ------------------------------------------------------------------------------
-- Q9: Are customers who are repeat buyers (more than 5 previous purchases) 
--     also likely to subscribe?
-- Purpose: Evaluate the cross-sell effectiveness of subscriptions on repeat buyers.
-- ------------------------------------------------------------------------------
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyer_count
FROM 
    customer
WHERE 
    previous_purchases > 5
GROUP BY 
    subscription_status;

-- ------------------------------------------------------------------------------
-- Q10: What is the revenue contribution of each age group?
-- Purpose: Identify the primary age demographics driving financial growth.
-- ------------------------------------------------------------------------------
SELECT 
    age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM 
    customer
GROUP BY 
    age_group
ORDER BY 
    total_revenue DESC;
